package infisical

import (
	"ehvg/packages/util"
	"fmt"
	"os"
	"slices"

	ifc "github.com/infisical/go-sdk"
	"github.com/spf13/cobra"
)


func NewSetEnvironmentCommand() *cobra.Command {
  var cmd = &cobra.Command{
    Use:    "set-environment",
    Aliases: []string{"set-env"},
    Args: cobra.MinimumNArgs(1),
    ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective){
      return CompletionListSites(), cobra.ShellCompDirectiveDefault 
    },
    PreRun: func(cmd *cobra.Command, args []string) {
      if !slices.Contains(CompletionListSites(), args[0]) {
        util.Red.Printf("invalid site specified: %v\n", args[0])
      }
    },
    Short:  "Change the current environment of your Docker Compose project",
    Run:    SetEnvironment,
  }

  cmd.Flags().StringP("env", "e", "dev", "The environment to set")
  cmd.Flags().StringP("project", "p", util.GetRepositoryName(), "The project to get the secrets for. Defaults to current git repository")

  return cmd
}

func SetEnvironment(cmd *cobra.Command, args []string) {
  client, err := GetClient()

  util.GetRepositoryName()

  return
  if err != nil {
    util.Red.Printf("unable to start infisical: %v", err)
    return
  }

  env, _ := cmd.Flags().GetString("env")

  secrets, _ := client.Secrets().List(ifc.ListSecretsOptions{
    ProjectID: DOK_CHECKOUT_INFISICAL_PROJECT_ID,
    Environment: env,
    IncludeImports: true,
  })
  if err != nil {
    util.Red.Printf("cannot retrieve environment: %v\n", err)
    return
  }

  if len(secrets) > 0 {
    util.White.Printf("Found %v variables. Exporting them to .env\n", util.Green.Sprint(len(secrets)))
    file, err := os.OpenFile(".env", os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
    if err != nil {
      util.Red.Printf("cannot create or open .env file: %v", err)
      return
    }

    defer file.Close()

    _, err = file.WriteString("# THIS FILE IS AUTOGENERATED FROM INFISICAL. ANY CHANGES MAY BE OVERWRITTEN WHEN CHANGING ENVIRONMENTS\n\n")
    if err != nil {
      util.Red.Printf("unable to write header to .env: %v", err)
    }

    for _, secret := range secrets {
      if secret.SecretComment != "" {
        _, err = file.WriteString(fmt.Sprintf("\n# %v\n", secret.SecretComment))  
        if err != nil {
          util.Red.Printf("unable to write comment to .env: %v", secret.SecretKey)
          return
        } 
      }
      _, err = file.WriteString(fmt.Sprintf("%v=%v\n", secret.SecretKey, secret.SecretValue))
      if err != nil {
        util.Red.Printf("unable to write secret to .env: %v", secret.SecretKey)
        return
      } 
    }
  } else {
    util.White.Printf("Found %v variables\n", util.Green.Sprint(0))
  }
}