package infisical

import (
	"ehvg/packages/util"
	"fmt"
	"os"
	"slices"

	ifc "github.com/infisical/go-sdk"
	"github.com/spf13/cobra"
)


func NewSetEnvironmentCommand() *cobra.Command {
  var cmd = &cobra.Command{
    Use:    "set-environment",
    Aliases: []string{"set-env"},
    Args: cobra.MinimumNArgs(1),
    ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective){
      return CompletionListSites(), cobra.ShellCompDirectiveDefault 
    },
    PreRun: func(cmd *cobra.Command, args []string) {
      if !slices.Contains(CompletionListSites(), args[0]) {
        util.Red.Printf("invalid site specified: %v\n", args[0])
      }
    },
    Short:  "Change the current environment of your Docker Compose project",
    Run:    SetEnvironment,
  }

  cmd.Flags().StringP("env", "e", "dev", "The environment to set")
  cmd.Flags().StringP("project", "p", util.GetRepositoryName(), "The project to get the secrets for. Defaults to current git repository")
  cmd.Flags().Bool("print", false, "Print the secrets to stdout instead of exporting them to .env")

  return cmd
}

func SetEnvironment(cmd *cobra.Command, args []string) {
  app := args[0]
  client, err := GetClient(app)
  if err != nil {
    util.Red.Printf("unable to start infisical: %v\n", err)
    return
  }
  
  project, _ := cmd.Flags().GetString("project")
  printSecrets, _ := cmd.Flags().GetBool("print")

  if project == "" {
    project = util.GetRepositoryName()
  }

  projectID, err := GetProjectIdByName(project, app)
  if err != nil {
    util.Red.Printf("Invalid project given: %v\n", project)
    return
  }

  env, _ := cmd.Flags().GetString("env")

  secrets, err := client.Secrets().List(ifc.ListSecretsOptions{
    ProjectID: projectID,
    Environment: env,
    IncludeImports: true,
  })
  if err != nil {
    util.Red.Printf("cannot retrieve environment: %v\n", err)
    return
  }

  if len(secrets) > 0 {
    if !printSecrets {
      util.White.Printf("Found %v variables. Exporting them to .env\n", util.Green.Sprint(len(secrets)))
    }

    file, err := os.OpenFile(".env", os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
    if err != nil {
      util.Red.Printf("cannot create or open .env file: %v", err)
      return
    }
    defer file.Close()

    if !printSecrets {
      file.WriteString("# THIS FILE IS AUTOGENERATED. ANY CHANGES MAY BE OVERWRITTEN WHEN CHANGING ENVIRONMENTS\n")
      file.WriteString("# Application: " +getFullApplicationName(app)+ "\n")
      file.WriteString("# Project: "+project+ "\n")
      file.WriteString("# Environment: "+env+ "\n\n")
      if err != nil {
        util.Red.Printf("unable to write header to .env: %v", err)
        return
      }
    }

    for _, secret := range secrets {
      if secret.SecretComment != "" {
        c := fmt.Sprintf("\n# %v\n", secret.SecretComment)

        if printSecrets {
          fmt.Print(c)
        } else {
          _, err = file.WriteString(c)
          if err != nil {
            util.Red.Printf("unable to write comment to .env: %v", secret.SecretKey)
            return
          } 
        }
      }

      s := fmt.Sprintf("%v=%v\n", secret.SecretKey, secret.SecretValue)
      if printSecrets {
        fmt.Print(s)
      } else {
        _, err = file.WriteString(s)
        if err != nil {
          util.Red.Printf("unable to write secret to .env: %v", err)
          return
        } 
      }
    }
  } else {
    util.White.Printf("Found %v variables\n", util.Green.Sprint(0))
  }
}