name: Build EHVGo application

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  set-version-tags:
    name: Set version tags
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.prepare-version-tags.outputs.version }}
    steps:
      - name: Prepare image version and tags
        id: prepare-version-tags
        run: |
            VERSION=${GITHUB_REF#refs/tags/}
            VERSION=${VERSION//\//-}
            echo "version=${VERSION}" >> $GITHUB_OUTPUT

  build-application:
    name: Build EHVGo
    runs-on: ubuntu-latest
    needs:
      - set-version-tags
    strategy:
      fail-fast: true
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with: 
          go-version: 1.22
      - name: Cache Executables
        id: cache-execs
        uses: actions/cache@v4
        with:
            key: dist-${{ github.run_id }}-${{ matrix.os }}-${{ matrix.arch }}
            path: dist/ehvgo-${{ needs.set-version-tags.outputs.version }}-${{ matrix.os }}-${{ matrix.arch }}.gz
      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          VERSION: ${{ needs.set-version-tags.outputs.version }}
        run: | 
          make -s build-cli && \
          gzip dist/ehvgo-${{ needs.set-version-tags.outputs.version }}-${{ matrix.os }}-${{ matrix.arch }}

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: 
      - set-version-tags
      - build-application
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
    steps:
      - name: Load Executables
        uses: actions/cache@v4
        with:
            key: dist-${{ github.run_id }}-${{ matrix.os }}-${{ matrix.arch }}
            path: dist/ehvgo-${{ needs.set-version-tags.outputs.version }}-${{ matrix.os }}-${{ matrix.arch }}.gz
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          make_latest: true
          files: |
            dist/ehvgo-*
      - name: install-aws-cli-action
        uses: unfor19/install-aws-cli-action@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::051772299350:role/S3GithubAccess
            role-session-name: DistUploadViaFederatedOIDC
            aws-region: eu-central-1
      - name: Upload to S3
        run: aws s3 cp dist/* s3://dist.ehealthsystems.nl/ehvgo/
        

