on:
  push:
    paths:
      - Formula/ehvgo.rb
  workflow_dispatch: {}

name: Test the package binaries

jobs:
  test-linux-amd64:
    name: Test binary on AMD64 arch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" && \
          echo >> /home/runner/.bashrc && \
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bashrc && \
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      - run: brew install Formula/ehvgo.rb
        env:
          PATH: "$HOME/.linuxbrew/bin:$PATH"
  test-darwin-arm64:
    name: Test binary on Apple Silicon arch
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" && \
          echo >> /Users/runner/.bash_profile && \
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/runner/.bash_profile && \
          eval "$(/opt/homebrew/bin/brew shellenv)"
      - run: brew install Formula/ehvgo.rb
      - run: ehvgo version